### ISSUE TITLE
Cannot install LROSE or RADX on OS X (10.12.3)

### ISSUE THREAD

**Issue by dstex** [NCAR/lrose-core#4]
I initially tried using the homebrew installation path, for both LROSE and the standalone RADX package, which yielded the following:
```
Dan-Stechman-MacBook-Pro:~ danstechman$ brew install https://github.com/NCAR/lrose-core/releases/download/lrose-20170314/lrose.rb

Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/danstechman/Library/Caches/Homebrew/Formula/lrose.rb:9:in `<class:Lrose>'
```
and
```
Dan-Stechman-MacBook-Pro:~ danstechman$ brew install https://github.com/NCAR/lrose-core/releases/download/radx-20170315/radx.rb
######################################################################## 100.0%
==> Downloading https://github.com/NCAR/lrose-core/releases/download/radx-20170315/radx-20170315.src.tgz
Already downloaded: /Users/danstechman/Library/Caches/Homebrew/radx-20170315.tgz
==> ./configure --prefix=/usr/local/Cellar/radx/20170315
Last 15 lines from /Users/danstechman/Library/Logs/Homebrew/radx/01.configure:
2017-04-13 17:55:51 -0600

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/radx/20170315


Do not report this issue to Homebrew/brew or Homebrew/core!
```
Where the complete output from the `01.configure` file referenced is given here:
[01.configure.txt](https://github.com/NCAR/lrose-core/files/921133/01.configure.txt)

Trying to manually build is similarly met with a slew of issues. Given a recent conversation with Mike Dixon, I will refrain from recreating and posting these (unless it would be helpful) as Mike noted he was aware of this problem already.

**Comment by burghart** [comment]
Hi Dan,

I've attached a new lrose.rb file which has a sha256 sum for the source
package in addition to the old sha1 sum. Can you try it out and see if it
gets further for you? Also, what's your OS version?

Thanks,

Chris

**Comment by stechma2** [comment]
Hi Chris,

I do not see the lrose.rb file you attached. My OS version is 10.12.3.

Dan

**Comment by burghart** [comment]
Oops, Github doesn't allow .rb attachments, but it does accept .zip.
[lrose.rb.zip](https://github.com/NCAR/lrose-core/files/922309/lrose.rb.zip)

**Comment by stechma2** [comment]
I get the same error unfortunately:

```
vpnpool-130-126-153-127:Downloads danstechman$ brew install lrose.rb
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/Users/danstechman/Downloads/lrose.rb:9:in `<class:Lrose>'
```

**Comment by burghart** [comment]
I was afraid of that. Here's a new one that has the sha1 removed completely, and only has sha256.
[lrose.rb.zip](https://github.com/NCAR/lrose-core/files/922325/lrose.rb.zip)

**Comment by stechma2** [comment]
Well that allowed for it to get a little further at least...

```
vpnpool-130-126-153-127:Downloads danstechman$ brew install lrose.rb
==> Downloading https://github.com/NCAR/lrose-core/releases/download/lrose-20170314/lrose-20170314.src.tgz
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/51408988/dbed40c8-08d7-11e7-8a91-9884192ede18.tgz?X-Amz-Algorithm=AWS4-HMAC-SHA256
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/lrose/20170314
Last 15 lines from /Users/danstechman/Library/Logs/Homebrew/lrose/01.configure:
2017-04-14 09:19:22 -0600

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/lrose/20170314


Do not report this issue to Homebrew/brew or Homebrew/core!
```

Contents of the `01.configure` file are:
```
2017-04-14 09:19:22 -0600

./configure
--disable-dependency-tracking
--prefix=/usr/local/Cellar/lrose/20170314


HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2b2083014299667116c854244c64df7281f09d2
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121, 1.7.0_79
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1489640002
X11: 2.7.8 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/netcdf/lib/pkgconfig:/usr/local/opt/fftw/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/hdf5/bin:/usr/local/opt/udunits/bin:/usr/local/opt/netcdf/bin:/usr/local/opt/fftw/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by swnesbitt** [comment]
All,

I tried this, and it seems that the configure script is not found in the top level of the install directory.  It is located in the `codebase` directory, but when I try to run configure in that directory, it fails with

```
snesbitt@pc176 ~/software/lrose-20170314.src/codebase$ ./configure --disable-dep
endency-tracking --prefix=/Users/snesbitt/software 
configure: netCDF 1.0
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

**Comment by swnesbitt** [comment]
I quickly entered a house of pain when I investigated this.  Apple's LLVM compiler issues, then makefile issues....

I am going to abandon my efforts on OS X and turn to an ubuntu vagrant box.

**Comment by mike-dixon** [comment]
We now have a well-tested brew install for lrose-core.
