### ISSUE TITLE
checkout_and_build_auto.py stops during build-libs

### ISSUE THREAD

**Issue by RubenImhoff** [NCAR/lrose-core#73]
[build-libs.log](https://github.com/NCAR/lrose-core/files/3202475/build-libs.log)
Dear Mike and others,

I encounter an error when I'm trying to install lrose-core (with as goal to eventually run TITAN). Until build-libs everything runs smoothly, but after a while in building the libs, the following error occurs:

```
Running cmd: make -j8 -k
Log file is: /tmp/lrose_build/logs/build-libs.log
   . . . .
Traceback (most recent call last):
    File "./checkout_and_build_auto.py", line 816, in <module>
        main()
    File "./checkout_and_build_auto.py", line 269, in main
        buildPackage()
    File "./checkout_and_build_auto.py", line 608, in BuildPackage
        shellCmd(cmd)
    File "./checkout_and_build_auto.py", line 608, in shellCmd
        retcode = subprocess.check_call(cmdToRun, shell=True)
    File "/home/WUR/imhof002/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
         raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make -j8 -k 1>> /tmp/lrose_build/logs/build-libs.log 2>&1' returned non-zero exit status 2.
```

Attached also the build-libs.log. 

Any idea what is causing this error?

Thanks a lot for your help!

Ruben

**Comment by RubenImhoff** [comment]
Hmm turns out my browser is too old for a proper code display and to attach the build-libs.log. I'm unfortunately not allowed to update the browser myself on this computer, but I'll send it later via another computer.

**Comment by RubenImhoff** [comment]
Found the error, apparently path to fftw3.h was missing.
